import type { CSSProperties } from 'react'

// 顶部标题栏共享样式，供 App 及各功能按钮组件复用，保证整条栏目视觉统一
export const topbarStyles: Record<string, CSSProperties> = {
  bar: {
    height: 52,
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 16px',
    borderBottom: '1px solid var(--line)',
    background: 'var(--bg-1)',
    gap: 12,
  },
  group: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    height: 34,
    padding: 3,
    background: 'var(--bg-0)',
    border: '1px solid var(--line)',
    borderRadius: 10,
    flexShrink: 0,
  },
  btn: {
    height: 28,
    padding: '0 10px',
    border: 0,
    background: 'transparent',
    color: 'var(--fg-1)',
    borderRadius: 7,
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    fontSize: 12,
    fontWeight: 500,
    fontFamily: 'inherit',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    flexShrink: 0,
    transition: 'background 120ms, color 120ms',
  },
  btnActive: {
    background: 'var(--accent-soft)',
    color: 'oklch(0.88 0.10 220)',
    boxShadow: 'inset 0 0 0 1px oklch(0.78 0.13 220 / 0.25)',
  },
  iconOnly: {
    width: 28,
    height: 28,
    padding: 0,
    display: 'grid',
    placeItems: 'center',
  },
  divider: { width: 1, height: 16, background: 'var(--line)', margin: '0 2px', flexShrink: 0 },
  status: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 11,
    color: 'var(--fg-2)',
    fontFamily: "'JetBrains Mono', monospace",
    whiteSpace: 'nowrap',
    flexShrink: 0,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 99,
    background: 'var(--success)',
    boxShadow: '0 0 0 3px oklch(0.74 0.16 150 / 0.18)',
    flexShrink: 0,
  },
  pathPill: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    height: 32,
    padding: '0 12px',
    background: 'var(--bg-0)',
    border: '1px solid var(--line)',
    borderRadius: 8,
    color: 'var(--fg-1)',
    fontSize: 12.5,
    minWidth: 0,
  },
  pathLabel: {
    color: 'var(--fg-3)',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: '0.4px',
    flexShrink: 0,
  },
  pathValue: {
    fontFamily: "'JetBrains Mono', monospace",
    color: 'var(--fg-0)',
    fontSize: 12,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: 280,
  },
}

export default topbarStyles
